# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 568ab7d372fde35590c5f99ce252e737fe6e31356cdcec59dbbeba591f9d26cb850adb73f473798bb8aace61d57baa622b4e8c210f2cbd88a11f05ba3f7688a4

test:
  secret_key_base: 465c5b119a8205daa747772e5987b1ce961c6009412349eae688f3a91d8bced0bc8463ca0fa2292989b6b25d7038ab54fd4ef1705a25cd74d2ed06f0e4d8bde9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
